# Generated by Django 4.2.7 on 2023-11-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doces', '0002_categoria_doce_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='doce',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='doces.categoria'),
            preserve_default=False,
        ),
    ]
